create table if not exists public.bot_users (
  telegram_user_id bigint primary key,
  active_agent_chat_id integer not null default 1,
  next_agent_chat_id integer not null default 2,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_chats (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null references public.bot_users(telegram_user_id) on delete cascade,
  agent_chat_id integer not null,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telegram_user_id, agent_chat_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null references public.bot_users(telegram_user_id) on delete cascade,
  agent_chat_id integer not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now(),
  foreign key (telegram_user_id, agent_chat_id)
    references public.agent_chats(telegram_user_id, agent_chat_id)
    on delete cascade
);

create index if not exists chat_messages_lookup_idx
  on public.chat_messages (telegram_user_id, agent_chat_id, id desc);
